config/routes.rb
Rails.application.routes.draw do
  devise_for :models
  resources :friends
  get 'home/about'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  #get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
	belongs_to :model
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy!

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :language, :country, :tandem_id, :model_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field form-group">
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field form-group">
    <%= form.label :language, style: "display: block" %>
    <%= form.text_field :language %>
  </div>

  <div class="field form-group">
    <%= form.label :country, style: "display: block" %>
    <%= form.text_field :country %>
  </div>

  <div class="field form-group">
    <%= form.label :tandem_id, style: "display: block" %>
    <%= form.text_field :tandem_id %>
  </div>

  <div class="field form-group">
    <%= form.number_field :model_id, 
    id: :friend_model_id, value: current_model.id,
    type: :hidden
     %>
  </div>
<br />
<br />

  <div class="actions">
    <%= form.submit class:"btn btn-secondary" %>
  </div>
  <br />

<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  <p>
    <strong>First name:</strong>
    <%= friend.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= friend.last_name %>
  </p>

  <p>
    <strong>Language:</strong>
    <%= friend.language %>
  </p>

  <p>
    <strong>Country:</strong>
    <%= friend.country %>
  </p>

  <p>
    <strong>Tandem:</strong>
    <%= friend.tandem_id %>
  </p>

</div>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend %> |
  <%= link_to "Back to friends", friends_path %>
</div>

app/views/friends/index.html.erb
<p id="notice"><%= notice %></p>

<br /><br />
<br /><br />

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Language</th>
      <th>Country</th>
      <th>Tandem</th>
      <th>Detail</th>
      <th colspan="3"></th>
   </tr>
 </thead>

 <tbody>
  <% @friends.each do |friend| %>
<tr>
          <td><%= friend.first_name %></td>
          <td><%= friend.last_name %></td>
          <td><%= friend.language %></td>
          <td><%= friend.country %></td>
          <td><%= friend.tandem_id %></td>
    <td>
      <%= link_to "Show this friend", friend %>
    </td>
     </tr>
  <% end %>
</tbody>
</table>
<%= link_to "New friend", new_friend_path, class:"btn btn-secondary" %>

app/views/friends/new.html.erb
<br />
<br />
<br />

<h3>Add a new friend</h3>

<%= render "form", friend: @friend %>

 <div>
    <%= link_to "Back to friends", friends_path, class:"btn btn-secondary" %>
  </div>

app/views/friends/show.html.erb
<p id="notice"><%= notice %></p>
<br />
<br />
<br />
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"><%= @friend.first_name %> <%= @friend.last_name %></h5>
    <h6 class="card-subtitle mb-2 text-body-secondary">from <%= @friend.country %></h6>
    <p class="card-text">My friend is fluently speaking <%= @friend.language %>  
    </p>
          <br />
<div class="modal-footer">
         <%= link_to "Edit this friend", edit_friend_path(@friend), class:"btn btn-secondary" %>
  <%= link_to "Back to friends", friends_path, class:"btn btn-dark" %>
<br /><br />

  <%= button_to "Destroy this friend", @friend, class:"btn btn-danger", method: :delete %>
      </div>
   
  </div>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
     <%= link_to 'Tandem Friends', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class='nav-item'><%= link_to 'About', home_about_path, class: "nav-link" %></li>
          <li class='nav-item'><%= link_to 'My Friends', friends_path, class: "nav-link" %></li>
          <li class='nav-item'><%= link_to 'Add Friend', new_friend_path, class: "nav-link" %></li>
          <li class='nav-item'><%= link_to 'Sign Up', new_model_registration_path, class: "nav-link" %></li>    
        <li class='nav-item'><%= link_to 'Sign In', new_model_session_path, class: "nav-link" %></li>
          <li class='nav-item'><%= link_to 'Edit Profile', edit_model_registration_path, class: "nav-link" %></li>

      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About us ...</h1>

app/views/home/index.html.erb
<h1>Helllo word</h1>
first ...

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    
    <title>Crudapp</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>

    <%= render 'home/header' %>
    <div class="container">
    <%= yield %>
  </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
  </body>
</html>